### ISSUE TITLE
Update fro Nicehash v2

### ISSUE THREAD

**Issue by GTAIPTV** [GarboMuffin/nicehash-calculator#15]
Can you update for NicehashV2 api?

https://docs.nicehash.com/

**Comment by ghost** [comment]
I'm looking into it

**Comment by ghost** [comment]
Most of the code for the new platform has been written. I'll do more testing before I replace the old API with the new one.

**Comment by GTAIPTV** [comment]
Sounds good.

Thank you. ;)

**Comment by ghost** [comment]
It has been updated. See https://github.com/GarboMuffin/nicehash-calculator#updating

**Comment by ghost** [comment]
Everything should be functionally identical to the old version, with the maybe notable exception that the calculation for "average" pricing (default) has changed slightly.
